namespace: kilip
name: olympus
version: 1.0.0
readme: README.md
authors:
- Anthonius Munthi <me@itstoni.com>
description: Home Server and Workstation Setup
license:
- MIT
license_file: 'LICENSE'
tags:
- openhab
- influxdb

dependencies: []

repository: https://github.com/kilip/ansible-collection-olympus

# The URL to any online docs
documentation: https://kilip.github.com/kilip/ansible-collection-olympus

# The URL to the homepage of the collection/project
homepage: https://kilip.github.com/kilip/ansible-collection-olympus

# The URL to the collection issue tracker
issues: https://github.com/kilip/ansible-collection-olympus/issues
