---
- import_tasks: apt.yml

- import_tasks: util.yml

- name: include user task
  import_tasks: user.yml

- import_tasks: gpg.yml
  when: gpg

- import_tasks: git.yml
  when: git

- import_tasks: ohmyzsh.yml
  when: ohmyzsh


- import_tasks: regolith.yml
  when: regolith

- import_tasks: rvm.yml
  become: yes
  become_user: "{{ zeus_user }}"
  when: rvm

- import_tasks: docker.yml
  when: docker

- import_tasks: virtualbox.yml
  when: vbox

- import_tasks: chrome.yml
  when: chrome

- import_tasks: nvm.yml
  when: nvm

- import_tasks: phpbrew.yml
  when: phpbrew
