- name: nvm ~> check existing installation
  become: true
  become_user: "{{ zeus_user }}"
  become_flags: '-s /bin/bash'
  command: "nvm --version"
  failed_when: false
  register: _nvm_stat
  changed_when: false

- name: nvm ~> download install script
  become: true
  become_user: "{{ zeus_user }}"
  when: _nvm_stat.rc != 0
  get_url:
    url: "http://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh"
    dest: /tmp/nvm-install.sh
    mode: u+x,g+x,o+x

- name: nvm ~> run install script
  become: true
  become_user: "{{ zeus_user }}"
  command: "/tmp/nvm-install.sh"
  when: _nvm_stat.rc != 0
  args:
    creates: "{{ zeus_home }}/.nvm/nvm.sh"
