- name: nvm ~> check existing installation
  stat:
    path: "{{ zeus_home }}/.nvm"
  failed_when: false
  register: _nvm_stat
  changed_when: false

- name: nvm ~> set install mode
  set_fact:
    nvm_install: no
  when: _nvm_stat.stat.isdir

- name: nvm ~> download install script
  become: true
  become_user: "{{ zeus_user }}"
  when: nvm_install
  get_url:
    url: "https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh"
    dest: "{{ nvm_install_sh }}"
    mode: u+x,g+x,o+x

- name: nvm ~> run install script
  become: true
  become_user: "{{ zeus_user }}"
  command: "{{ nvm_install_sh }}"
  when: nvm_install
  args:
    creates: "{{ zeus_home }}/.nvm/nvm.sh"
