- name: phpbrew ~> check existing installation
  stat:
    path: "{{ zeus_home }}/.phpbrew"
  register: _phpbrew_dir

- name: phpbrew ~> set phpbrew install mode
  changed_when: false
  failed_when: false
  set_fact:
    phpbrew_install: no
  when: _phpbrew_dir.stat.isdir

- name: phpbrew => install requirements
  package:
    name:
      - build-essential
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxslt-dev
      - libcurl4-gnutls-dev
      - zlib1g-dev
      - libpng-dev
      - libonig-dev
      - libzip-dev
      - pkg-config
      - php-cli
      - php-bz2
    state: present
  when: phpbrew_install

- name: phpbrew => downloading phpbrew
  get_url:
    url: https://github.com/phpbrew/phpbrew/releases/latest/download/phpbrew.phar
    dest: /usr/local/bin/phpbrew
    mode: u=rwx,g=rwx,o=rx
  when: phpbrew_install

- name: phpbrew => initialize phpbrew
  become: yes
  become_user: "{{ zeus_user }}"
  command: phpbrew init
  changed_when: false
  args:
    creates: "{{ zeus_home }}/.phpbrew"
  when: phpbrew_install

- name: phpbrew ~> setup bash
  become: yes
  become_user: "{{ zeus_user }}"
  lineinfile:
    path: "{{ zeus_home }}/.bashrc"
    regexp: '^source.*\.phpbrew/bashrc'
    line: "source {{ zeus_home }}/.phpbrew/bashrc"
  when: phpbrew_install
