- name: regolith ~> configure apt-repository
  apt_repository:
    repo: ppa:regolith-linux/release
    state: present
    update_cache: yes

- name: regolith ~> start installation
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - regolith-desktop
    - i3xrocks-net-traffic
    - i3xrocks-cpu-usage
    - i3xrocks-time
