---
- name: Converge Hosts
  hosts: all
  collections:
  - kilip.olympus
  tasks:
    - name: "running olympus role"
      include_role:
        name: olympus

  vars:
    zeus_gpg: no
    gpg_key_id: foo
    gpg_private_key: bar
    
    zeus_util:
    - cockpit
    - vim
    - bash-completion

    grafana_security:
      admin_user: admin
      admin_password: admin

    openhab_configure_nginx: yes
    openhab_nginx_users:
      - username: openhab
        password: openhab
    openhab_nginx_allow:
      - 10.0.0.0/24
      - 10.10.10.0/24